spring:
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    cache: false
  jackson:
    time-zone: GMT+8
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      ## 如果后端项目服务器和数据库服务器不在同一台主机，则需要修改localhost为数据库服务器ip地址
      url: jdbc:mysql://210.30.97.22:3306/fmmall2?characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: root
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.qfedu.fmmall.entity

logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error
